@startuml 系统标记

!include <c4/c4_container>
!include <c4/c4_component>
!include <c4/c4_deployment>

!include <office/users/user>
!include <office/users/users>
!include <office/users/approver>
!include <office/users/user_external>
!include <office/users/administrator>
!include <office/servers/application_server>
!include <office/servers/database_server>
!include <office/services/3rd_party_service>
!include <office/services/access_services>
!include <office/concepts/application_windows>
!include <office/concepts/app_part>
!include <office/databases/database>
!include <office/communications/messages_queued>

AddPersonTag(users, $sprite="users", $legendText="应用用户")
AddPersonTag(admins, $sprite="administrator", $legendText="系统管理员")
AddPersonTag(maintainers, $sprite="approver", $legendText="运维人员")
AddExternalPersonTag(ext_person, $sprite="user_external", $legendText="外部人员")

AddSystemTag(web_s, $sprite="application_server", $legendText="内部服务系统")
AddSystemTag(module_s, $sprite="access_services", $legendText="内部模块")
AddSystemTag(desktop_s, $sprite="application_windows", $legendText="桌面应用系统")
AddSystemTag(db_s, $sprite="database_server", $legendText="数据库系统")
AddSystemTag(queue_s, $sprite="messages_queued", $legendText="队列系统")
AddExternalSystemTag(ext_s, $sprite="application_server", $legendText="外部业务系统")
AddExternalSystemTag(ext_db_s, $sprite="database_server", $legendText="外部数据库系统")
AddExternalSystemTag(ext_queue_s, $sprite="messages_queued", $legendText="外部队列系统")
AddExternalSystemTag(offline_s, $sprite="3rd_party_service", $legendText="外部线下业务系统")

AddNodeTag(n, $legendText="服务节点")

AddContainerTag(c, $legendText="服务容器", $sprite="app_part,scale=0.55", $legendSprite="app_part,scale=0.25")
AddContainerTag(db_c, $legendText="数据服务容器", $sprite="database,scale=0.55", $legendSprite="database,scale=0.25")
AddContainerTag(queue_c, $legendText="队列容器", $sprite="messages_queued,scale=0.55", $legendSprite="messages_queued,scale=0.25")
AddExternalContainerTag(ext_c, $legendText="外部服务容器", $sprite="app_part,scale=0.55", $legendSprite="app_part,scale=0.25")
AddExternalContainerTag(ext_db_c, $legendText="外部数据容器", $sprite="database,scale=0.55", $legendSprite="database,scale=0.25")
AddExternalContainerTag(ext_queue_c, $legendText="外部队列容器", $sprite="messages_queued,scale=0.55", $legendSprite="messages_queued,scale=0.25")

AddComponentTag(comp, $legendText="标准组件", $legendText="表示层组件", $sprite="app_part,scale=0.55", $legendSprite="app_part,scale=0.25")
AddComponentTag(present_comp, $bgColor="#AFC8B2", $legendText="表示层组件", $sprite="app_part,scale=0.55", $legendSprite="app_part,scale=0.25")
AddComponentTag(service_comp, $bgColor="#8FA678", $legendText="业务层组件", $sprite="app_part,scale=0.55", $legendSprite="app_part,scale=0.25")
AddComponentTag(persist_comp, $bgColor="#BFB3B4", $legendText="持久层组件", $sprite="app_part,scale=0.55", $legendSprite="app_part,scale=0.25")
AddComponentTag(db_comp, $legendText="数据库组件", $sprite="database,scale=0.55", $legendSprite="database,scale=0.25")
AddComponentTag(queue_comp, $legendText="消息组件", $sprite="messages_queued,scale=0.55", $legendSprite="messages_queued,scale=0.25")
AddExternalComponentTag(ext_comp, $legendText="外部组件", $sprite="app_part,scale=0.55", $legendSprite="app_part,scale=0.25")
AddExternalComponentTag(ext_db_comp, $legendText="外部数据组件", $sprite="database,scale=0.55", $legendSprite="database,scale=0.25")
AddExternalComponentTag(ext_queue_comp, $legendText="外部队列组件", $sprite="messages_queued,scale=0.55", $legendSprite="messages_queued,scale=0.25")

AddRelTag(r, $lineStyle=Line(), $legendText="业务关联")
AddRelTag(b_r, $lineStyle=BoldLine(), $legendText="关键业务关联")
AddRelTag(v_r, $textColor="#aaa", $lineColor="#aaa", $lineStyle=DashedLine(), $legendText="非业务关联")
AddRelTag(offline_r, $textColor="#aaf", $lineColor="#aaf", $lineStyle=DottedLine(), $legendText="外部关联")

!function $defLabel($label, $defVal)
  !if ($label == "")
    !$label = $defVal
  !endif
  !return $label
!endfunction

!unquoted procedure Users($alias, $label="", $descr="", $sprite="", $link="")
  Person($alias, $defLabel($label, "用户"), $descr, $sprite, "users", $link)
!endprocedure

!unquoted procedure Admins($alias, $label="", $descr="", $sprite="", $link="")
  Person($alias, $defLabel($label, "管理员"), $descr, $sprite, "admins", $link)
!endprocedure

!unquoted procedure Maintainers($alias, $label="", $descr="", $sprite="", $link="")
  Person($alias, $defLabel($label, "运维人员"), $descr, $sprite, "maintainers", $link)
!endprocedure

!unquoted procedure ExtUsers($alias, $label="", $descr="", $sprite="", $link="")
  Person($alias, $defLabel($label, "外部人员"), $descr, $sprite, "ext_person", $link)
!endprocedure

!unquoted procedure AppServer($alias, $label="", $descr="", $sprite="", $link="")
  System($alias, $defLabel($label, "应用服务"), $descr, $sprite, "web_s", $link)
!endprocedure

!unquoted procedure AppModule($alias, $label="", $descr="", $sprite="", $link="")
  System($alias, $defLabel($label, "服务模块"), $descr, $sprite, "module_s", $link)
!endprocedure

!unquoted procedure AppDesktop($alias, $label="", $descr="", $sprite="", $link="")
  System($alias, $defLabel($label, "桌面应用"), $descr, $sprite, "desktop_s", $link)
!endprocedure

!unquoted procedure DBServer($alias, $label="", $descr="", $sprite="", $link="")
  SystemDb($alias, $defLabel($label, "数据库服务"), $descr, $sprite, "db_s", $link)
!endprocedure

!unquoted procedure QueueServer($alias, $label="", $descr="", $sprite="", $link="")
  SystemQueue($alias, $defLabel($label, "队列服务"), $descr, $sprite, "queue_s", $link)
!endprocedure

!unquoted procedure ExtServer($alias, $label="", $descr="", $sprite="", $link="")
  System_Ext($alias, $defLabel($label, "外部应用服务"), $descr, $sprite, "ext_s", $link)
!endprocedure

!unquoted procedure ExtDBServer($alias, $label="", $descr="", $sprite="", $link="")
  SystemDb_Ext($alias, $defLabel($label, "外部数据库服务"), $descr, $sprite, "ext_db_s", $link)
!endprocedure

!unquoted procedure ExtQueueServer($alias, $label="", $descr="", $sprite="", $link="")
  SystemQueue($alias, $defLabel($label, "外部队列服务"), $descr, $sprite, "ext_queue_s", $link)
!endprocedure

!unquoted procedure Offline($alias, $label="", $descr="", $sprite="", $link="")
  System($alias, $defLabel($label, "线下系统"), $descr, $sprite, "offline_s", $link)
!endprocedure

!unquoted procedure Container($alias, $label="", $descr="", $techn="", $sprite="", $link="")
  Container($alias, $defLabel($label, "标准容器"), $descr, $techn, $sprite, "c", $link)
!endprocedure

!unquoted procedure ExtContainer($alias, $label="", $descr="", $techn="", $sprite="", $link="")
  Container($alias, $defLabel($label, "外部容器"), $descr, $techn, $sprite, "ext_c", $link)
!endprocedure

!unquoted procedure DataContainer($alias, $label="", $descr="", $techn="", $sprite="", $link="")
  ContainerDb($alias, $defLabel($label, "数据容器"), $descr, $techn, $sprite, "db_c", $link)
!endprocedure

!unquoted procedure ExtDataContainer($alias, $label="", $descr="", $techn="", $sprite="", $link="")
  ContainerDb_Ext($alias, $defLabel($label, "外部数据容器"), $descr, $techn, $sprite, "ext_db_c", $link)
!endprocedure

!unquoted procedure ContainerQueue($alias, $label="", $descr="", $techn="", $sprite="", $link="")
  ContainerQueue($alias, $defLabel($label, "队列容器"), $descr, $techn, $sprite, "queue_c", $link)
!endprocedure

!unquoted procedure ExtContainerQueue($alias, $label="", $descr="", $techn="", $sprite="", $link="")
  ContainerQueue_Ext($alias, $defLabel($label, "外部队列容器"), $descr, $techn, $sprite, "ext_queue_c", $link)
!endprocedure

!unquoted procedure Component($alias, $label="", $descr="", $techn="", $sprite="", $link="")
  Component($alias, $defLabel($label, "标准组件"), $descr, $techn, $sprite, "comp", $link)
!endprocedure

!unquoted procedure PresentComp($alias, $label="", $descr="", $techn="", $sprite="", $link="")
  Component($alias, $defLabel($label, "表现层组件"), $descr, $techn, $sprite, "present_comp", $link)
!endprocedure

!unquoted procedure ServiceComp($alias, $label="", $descr="", $techn="", $sprite="", $link="")
  Component($alias, $defLabel($label, "业务层组件"), $descr, $techn, $sprite, "service_comp", $link)
!endprocedure

!unquoted procedure PersistComp($alias, $label="", $descr="", $techn="", $sprite="", $link="")
  Component($alias, $defLabel($label, "持久层组件"), $descr, $techn, $sprite, "persist_comp", $link)
!endprocedure

!unquoted procedure DBComp($alias, $label="", $descr="", $techn="", $sprite="", $link="")
  Component($alias, $defLabel($label, "数据层组件"), $descr, $techn, $sprite, "db_comp", $link)
!endprocedure

!unquoted procedure QueueComp($alias, $label="", $descr="", $techn="", $sprite="", $link="")
  ComponentQueue($alias, $defLabel($label, "数据层组件"), $descr, $techn, $sprite, "queue_comp", $link)
!endprocedure

!unquoted procedure ExtComp($alias, $label="", $descr="", $techn="", $sprite="", $link="")
  Component_Ext($alias, $defLabel($label, "外部组件"), $descr, $techn, $sprite, "ext_comp", $link)
!endprocedure

!unquoted procedure ExtDBComp($alias, $label="", $descr="", $techn="", $sprite="", $link="")
  ComponentDb_Ext($alias, $defLabel($label, "外部数据组件"), $descr, $techn, $sprite, "ext_db_comp", $link)
!endprocedure

!unquoted procedure ExtQueueComp($alias, $label="", $descr="", $techn="", $sprite="", $link="")
  ComponentQueue_Ext($alias, $defLabel($label, "外部队列组件"), $descr, $techn, $sprite, "ext_queue_comp", $link)
!endprocedure

!unquoted procedure DNode($alias, $label="", $type="", $descr="", $sprite="", $link="")
  Deployment_Node($alias, $defLabel($label, "系统节点"), $type, $descr, $sprite, $tags="n", $link)
!endprocedure

!unquoted procedure DNode_L($alias, $label="", $type="", $descr="", $sprite="", $link="")
  Deployment_Node_L($alias, $defLabel($label, "系统节点"), $type, $descr, $sprite, "n", $link)
!endprocedure

!unquoted procedure DNode_R($alias, $label="", $type="", $descr="", $sprite="", $link="")
  Deployment_Node_R($alias, $defLabel($label, "系统节点"), $type, $descr, $sprite, "n", $link)
!endprocedure

!unquoted procedure Rel($from, $to, $label="", $type="", $descr="", $sprite="", $link="")
  Rel($from, $to, $defLabel($label, " "), $type, $descr, $sprite, "r", $link)
!endprocedure

!unquoted procedure Rel_U($from, $to, $label="", $type="", $descr="", $sprite="", $link="")
  Rel_U($from, $to, $defLabel($label, " "), $type, $descr, $sprite, "r", $link)
!endprocedure

!unquoted procedure Rel_D($from, $to, $label="", $type="", $descr="", $sprite="", $link="")
  Rel_D($from, $to, $defLabel($label, " "), $type, $descr, $sprite, "r", $link)
!endprocedure

!unquoted procedure Rel_U($from, $to, $label="", $type="", $descr="", $sprite="", $link="")
  Rel_U($from, $to, $defLabel($label, " "), $type, $descr, $sprite, "r", $link)
!endprocedure

!unquoted procedure Rel_D($from, $to, $label="", $type="", $descr="", $sprite="", $link="")
  Rel_D($from, $to, $defLabel($label, " "), $type, $descr, $sprite, "r", $link)
!endprocedure

!unquoted procedure VRel($from, $to, $label="", $type="", $descr="", $sprite="", $link="")
  Rel($from, $to, $defLabel($label, " "), $type, $descr, $sprite, "v_r", $link)
!endprocedure

!unquoted procedure VRel_U($from, $to, $label="", $type="", $descr="", $sprite="", $link="")
  Rel_U($from, $to, $defLabel($label, " "), $type, $descr, $sprite, "v_r", $link)
!endprocedure

!unquoted procedure VRel_D($from, $to, $label="", $type="", $descr="", $sprite="", $link="")
  Rel_D($from, $to, $defLabel($label, " "), $type, $descr, $sprite, "v_r", $link)
!endprocedure

!unquoted procedure VRel_U($from, $to, $label="", $type="", $descr="", $sprite="", $link="")
  Rel_U($from, $to, $defLabel($label, " "), $type, $descr, $sprite, "v_r", $link)
!endprocedure

!unquoted procedure VRel_D($from, $to, $label="", $type="", $descr="", $sprite="", $link="")
  Rel_D($from, $to, $defLabel($label, " "), $type, $descr, $sprite, "v_r", $link)
!endprocedure

!unquoted procedure ORel($from, $to, $label="", $type="", $descr="", $sprite="", $link="")
  Rel($from, $to, $defLabel($label, " "), $type, $descr, $sprite, "offline_r", $link)
!endprocedure

!unquoted procedure ORel_U($from, $to, $label="", $type="", $descr="", $sprite="", $link="")
  Rel_U($from, $to, $defLabel($label, " "), $type, $descr, $sprite, "offline_r", $link)
!endprocedure

!unquoted procedure ORel_D($from, $to, $label="", $type="", $descr="", $sprite="", $link="")
  Rel_D($from, $to, $defLabel($label, " "), $type, $descr, $sprite, "offline_r", $link)
!endprocedure

!unquoted procedure ORel_U($from, $to, $label="", $type="", $descr="", $sprite="", $link="")
  Rel_U($from, $to, $defLabel($label, " "), $type, $descr, $sprite, "offline_r", $link)
!endprocedure

!unquoted procedure ORel_D($from, $to, $label="", $type="", $descr="", $sprite="", $link="")
  Rel_D($from, $to, $defLabel($label, " "), $type, $descr, $sprite, "offline_r", $link)
!endprocedure

!unquoted procedure BRel($from, $to, $label="", $type="", $descr="", $sprite="", $link="")
  Rel($from, $to, $defLabel($label, " "), $type, $descr, $sprite, "b_r", $link)
!endprocedure

!unquoted procedure BRel_U($from, $to, $label="", $type="", $descr="", $sprite="", $link="")
  Rel_U($from, $to, $defLabel($label, " "), $type, $descr, $sprite, "b_r", $link)
!endprocedure

!unquoted procedure BRel_D($from, $to, $label="", $type="", $descr="", $sprite="", $link="")
  Rel_D($from, $to, $defLabel($label, " "), $type, $descr, $sprite, "b_r", $link)
!endprocedure

!unquoted procedure BRel_U($from, $to, $label="", $type="", $descr="", $sprite="", $link="")
  Rel_U($from, $to, $defLabel($label, " "), $type, $descr, $sprite, "b_r", $link)
!endprocedure

!unquoted procedure BRel_D($from, $to, $label="", $type="", $descr="", $sprite="", $link="")
  Rel_D($from, $to, $defLabel($label, " "), $type, $descr, $sprite, "b_r", $link)
!endprocedure

!unquoted procedure BiRel($from, $to, $label="", $type="", $descr="", $sprite="", $link="")
  BiRel($from, $to, $defLabel($label, " "), $type, $descr, $sprite, "r", $link)
!endprocedure

!unquoted procedure BiRel_U($from, $to, $label="", $type="", $descr="", $sprite="", $link="")
  BiRel_U($from, $to, $defLabel($label, " "), $type, $descr, $sprite, "r", $link)
!endprocedure

!unquoted procedure BiRel_D($from, $to, $label="", $type="", $descr="", $sprite="", $link="")
  BiRel_D($from, $to, $defLabel($label, " "), $type, $descr, $sprite, "r", $link)
!endprocedure

!unquoted procedure BiRel_U($from, $to, $label="", $type="", $descr="", $sprite="", $link="")
  BiRel_U($from, $to, $defLabel($label, " "), $type, $descr, $sprite, "r", $link)
!endprocedure

!unquoted procedure BiRel_D($from, $to, $label="", $type="", $descr="", $sprite="", $link="")
  BiRel_D($from, $to, $defLabel($label, " "), $type, $descr, $sprite, "r", $link)
!endprocedure

!unquoted procedure BiVRel($from, $to, $label="", $type="", $descr="", $sprite="", $link="")
  BiRel($from, $to, $defLabel($label, " "), $type, $descr, $sprite, "v_r", $link)
!endprocedure

!unquoted procedure BiVRel_U($from, $to, $label="", $type="", $descr="", $sprite="", $link="")
  BiRel_U($from, $to, $defLabel($label, " "), $type, $descr, $sprite, "v_r", $link)
!endprocedure

!unquoted procedure BiVRel_D($from, $to, $label="", $type="", $descr="", $sprite="", $link="")
  BiRel_D($from, $to, $defLabel($label, " "), $type, $descr, $sprite, "v_r", $link)
!endprocedure

!unquoted procedure BiVRel_U($from, $to, $label="", $type="", $descr="", $sprite="", $link="")
  BiRel_U($from, $to, $defLabel($label, " "), $type, $descr, $sprite, "v_r", $link)
!endprocedure

!unquoted procedure BiVRel_D($from, $to, $label="", $type="", $descr="", $sprite="", $link="")
  BiRel_D($from, $to, $defLabel($label, " "), $type, $descr, $sprite, "v_r", $link)
!endprocedure

!unquoted procedure BiORel($from, $to, $label="", $type="", $descr="", $sprite="", $link="")
  BiRel($from, $to, $defLabel($label, " "), $type, $descr, $sprite, "offline_r", $link)
!endprocedure

!unquoted procedure BiORel_U($from, $to, $label="", $type="", $descr="", $sprite="", $link="")
  BiRel_U($from, $to, $defLabel($label, " "), $type, $descr, $sprite, "offline_r", $link)
!endprocedure

!unquoted procedure BiORel_D($from, $to, $label="", $type="", $descr="", $sprite="", $link="")
  BiRel_D($from, $to, $defLabel($label, " "), $type, $descr, $sprite, "offline_r", $link)
!endprocedure

!unquoted procedure BiROel_U($from, $to, $label="", $type="", $descr="", $sprite="", $link="")
  BiRel_U($from, $to, $defLabel($label, " "), $type, $descr, $sprite, "offline_r", $link)
!endprocedure

!unquoted procedure BiORel_D($from, $to, $label="", $type="", $descr="", $sprite="", $link="")
  BiRel_D($from, $to, $defLabel($label, " "), $type, $descr, $sprite, "offline_r", $link)
!endprocedure

!unquoted procedure BiBRel($from, $to, $label="", $type="", $descr="", $sprite="", $link="")
  BiRel($from, $to, $defLabel($label, " "), $type, $descr, $sprite, "b_r", $link)
!endprocedure

!unquoted procedure BiBRel_U($from, $to, $label="", $type="", $descr="", $sprite="", $link="")
  BiRel_U($from, $to, $defLabel($label, " "), $type, $descr, $sprite, "b_r", $link)
!endprocedure

!unquoted procedure BiBRel_D($from, $to, $label="", $type="", $descr="", $sprite="", $link="")
  BiRel_D($from, $to, $defLabel($label, " "), $type, $descr, $sprite, "b_r", $link)
!endprocedure

!unquoted procedure BiBRel_U($from, $to, $label="", $type="", $descr="", $sprite="", $link="")
  BiRel_U($from, $to, $defLabel($label, " "), $type, $descr, $sprite, "b_r", $link)
!endprocedure

!unquoted procedure BiBRel_D($from, $to, $label="", $type="", $descr="", $sprite="", $link="")
  BiRel_D($from, $to, $defLabel($label, " "), $type, $descr, $sprite, "b_r", $link)
!endprocedure
@enduml
