@startuml 系统标记
!include <c4/c4_container>
!include <c4/c4_deployment>

!include <office/users/user>
!include <office/users/users>
!include <office/users/approver>
!include <office/users/user_external>
!include <office/users/administrator>
!include <office/servers/application_server>
!include <office/servers/database_server>
!include <office/services/3rd_party_service>
!include <office/services/access_services>
!include <office/concepts/application_windows>

AddPersonTag(users, $sprite="users", $legendText="应用用户")
AddPersonTag(admins, $sprite="administrator", $legendText="系统管理员")
AddPersonTag(maintainers, $sprite="approver", $legendText="运维人员")
AddExternalPersonTag(ext_person, $sprite="user_external", $legendText="外部人员")

AddSystemTag(web, $sprite="application_server", $legendText="内部服务系统")
AddSystemTag(module, $sprite="access_services", $legendText="内部模块")
AddSystemTag(desktop, $sprite="application_windows", $legendText="桌面应用系统")
AddSystemTag(database, $sprite="database_server", $legendText="数据库系统")
AddExternalSystemTag(ext, $sprite="application_server", $legendText="外部业务系统")
AddExternalSystemTag(offline, $sprite="3rd_party_service", $legendText="外部线下业务系统")

AddNodeTag(n, $legendText="服务节点")
AddContainerTag(c, $legendText="服务容器")
AddExternalContainerTag(ext_c, $legendText="外部服务容器")

AddRelTag(maintain, $textColor="#aaa", $lineColor="#aaa", $lineStyle=DashedLine(), $legendText="维护操作")
AddRelTag(offline, $textColor="#aaf", $lineColor="#aaf", $lineStyle=DashedLine(), $legendText="线下业务")

AddContainerTag(present, $bgColor="#66CDAA", $legendText="表示层组件")
AddContainerTag(service, $bgColor="#458B74", $legendText="业务层组件")

!unquoted procedure Users($alias, $label="", $descr="", $sprite="", $link="")
  !if ($label == "")
    $label = "用户"
  !endif
  Person($alias, $label, $descr, $sprite, "users", $link)
!endprocedure

!unquoted procedure Admins($alias, $label="", $descr="", $sprite="", $link="")
  !if ($label == "")
    $label = "管理员"
  !endif
  Person($alias, $label, $descr, $sprite, "admins", $link)
!endprocedure

!unquoted procedure Maintainers($alias, $label="", $descr="", $sprite="", $link="")
  !if ($label == "")
    $label = "运维人员"
  !endif
  Person($alias, $label, $descr, $sprite, "maintainers", $link)
!endprocedure

!unquoted procedure ExtUsers($alias, $label="", $descr="", $sprite="", $link="")
  !if ($label == "")
    $label = "外部人员"
  !endif
  Person($alias, $label, $descr, $sprite, "ext_person", $link)
!endprocedure

!unquoted procedure AppServer($alias, $label="", $descr="", $sprite="", $link="")
  !if ($label == "")
    $label = "应用服务器"
  !endif
  System($alias, $label, $descr, $sprite, "web", $link)
!endprocedure

!unquoted procedure AppModule($alias, $label="", $descr="", $sprite="", $link="")
  !if ($label == "")
    $label = "应用模块"
  !endif
  System($alias, $label, $descr, $sprite, "module", $link)
!endprocedure

!unquoted procedure AppDesktop($alias, $label="", $descr="", $sprite="", $link="")
  !if ($label == "")
    $label = "桌面应用"
  !endif
  System($alias, $label, $descr, $sprite, "desktop", $link)
!endprocedure

!unquoted procedure AppServer($alias, $label="", $descr="", $sprite="", $link="")
  !if ($label == "")
    $label = "应用服务器"
  !endif
  System($alias, $label, $descr, $sprite, "web", $link)
!endprocedure

!unquoted procedure Database($alias, $label="", $descr="", $sprite="", $link="")
  !if ($label == "")
    $label = "数据库服务器"
  !endif
  System($alias, $label, $descr, $sprite, "database", $link)
!endprocedure

!unquoted procedure AppServerExt($alias, $label="", $descr="", $sprite="", $link="")
  !if ($label == "")
    $label = "外部应用服务器"
  !endif
  System($alias, $label, $descr, $sprite, "ext", $link)
!endprocedure

!unquoted procedure OfflineSystem($alias, $label="", $descr="", $sprite="", $link="")
  !if ($label == "")
    $label = "线下系统"
  !endif
  System($alias, $label, $descr, $sprite, "offline", $link)
!endprocedure
@enduml
