@startuml [C4] System Context Diagram

title 首件包模块系统上下文图

scale 1

!include <c4/c4_container>
!include <tupadr3/font-awesome/users>
!include <tupadr3/font-awesome/user>

' LAYOUT_TOP_DOWN()
' LAYOUT_LEFT_RIGHT()
' LAYOUT_WITH_LEGEND()
' LAYOUT_AS_SKETCH()

Person(purchaser, "采购商", "零件采购商角色", "users")

Person(supplier, "供应商", "零件生产制造角色", "users")

Person(admin, "系统管理员", "系统管理角色", "user")

System(FAI_service, "首件包管理模块 (内网)", "部署在采购商内网环境的交付协同模块\n[无法和外部联通]")

System(FAI_desktop, "首件包离线编辑器", "可以离线运行的首件包编辑器\n[桌面版本]")

System_Ext(UFIDA, "用友中台系统", "系统集成 | 应用部署 | 消息通知")

System_Ext(electric, "上海电气系统", "供应链管理 | 供应商寻源 | 交付协同")

System_Ext(landray, "蓝凌 OA 系统", "工作流")

SystemDb(dm_db, "达梦数据库系统", "数据存储")

Rel(supplier, FAI_desktop, "编写收件说明书")

Rel(FAI_desktop, FAI_service, "管理首件包")

Rel(FAI_service, dm_db, "数据访问/存储")

Rel(FAI_service, UFIDA, "用户认证, 消息通知")

Rel(FAI_service, landray, "审批, 表单")

Rel(FAI_service, electric, "待办事项")

Rel(purchaser, FAI_service, "首件包审核, 审批")

Rel(admin, FAI_service, "系统管理")

@enduml