@startuml er-demo

title ER 模型图

top to bottom direction

' 定义实体
entity Org {
    * id: string <<PK>>
    --
    name: string
}

entity User {
    * id: string <<PK>>
    --
    name: string
}

entity Department {
    * id: string <<PK>>
    --
    parent_id: string
    name: string
}

entity Employee {
    * id: string <<PK>>
    --
    * title: string
}

' 定义关系
' || One
' |o
' o| One or Zero
' |{
' }| Many
' o{
' }o Many or Zero
' -- 直接连接
' .. 间接连接 
' * 非空
' <<PK>>, <<FK>>, <<IX>>, <<UX>> 主键, 外键, 索引, 唯一索引

' One to One (or Zero) 
User ||--o| Employee

' One to Many (or Zero)
Org ||--o{ Employee

' One to Many (or Zero)
Org ||--o{ Department

' Many to Many (or Zero)
Department }|..o{ Employee

' One to Many (Self connect)
Department ||--o{ Department

@enduml